### ISSUE TITLE
[Feature]: Provide drop-in replacements of wordpress features like wp-cli, wp mail, wpdb, hooks...

### ISSUE THREAD

**Issue by amirhmoradi** [sniccowp/sniccowp#222]
### Thanks for taking the time to fill out this feature request!"

- [X] I have searched the issue tracker for similar requests

### Which @snicco/* package(s) are relevant/related of the feature request?

monorepo, better-wp-api, better-wp-cache, better-wp-cli, better-wp-hooks, better-wp-mail, better-wpdb

### Description

Hi, thanks for the great snicco framework. I believe there would be great impact if some of the components would be available as drop-in replacements for current wordpress features or tools. 
For example, I would love to install betterwp-cli and it would replace (in a transparent manner for me and for other plugins and tools), the wp-cli tool.
Same goes for betterwpdb : it would be great is it would overtake in a transparent manner the current wpdb object and add all the great feautres you have.

This approach would not only benefit developpers of new components/plugins, but also help reach a lot more users by bringing them great value (features and security), without re-writing their plugins or touching wordpress.

### Proposed solution

I do not have the proposed solution, but on an abstract level, there should be a way to wrap current tools and take them over with the new ones provided by snicco.

**Comment by calvinalkan** [comment]
Hey @amirhmoradi 

I don't think that's possible.

For example, to make WordPress use better-wpdb, you'd somehow need to rewrite all queries on the fly so that it uses the correct syntax for prepared queries with question marks.

That sounds very buggy to me.

This entire project is more so for developers to use in their projects/plugins.

I'm closing this for now, but feel free to re-open this if you have any concrete idea on how any component could be swapped out behind the scenes.
